---
name: DAS Metta Parser Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  build-binary:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Dockerfile
        run: ./scripts/docker_image_build.sh

      - name: Build Binary
        run: ./scripts/build.sh

      - name: Upload syntax_check artifact
        uses: actions/upload-artifact@v4
        with:
          name: syntax_check
          path: bin/syntax_check

      - name: Upload db_loader artifact
        uses: actions/upload-artifact@v4
        with:
          name: db_loader
          path: bin/db_loader

  build-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Dockerfile
        run: |-
          docker build -f ./docker/Dockerfile.toolbox -t trueagi/das:${{ github.event.inputs.version }}-metta-parser .
          docker image tag trueagi/das:${{ github.event.inputs.version }}-metta-parser trueagi/das:latest-metta-parser

      - name: Push Image to Registry
        run: |-
          docker image push trueagi/das:${{ github.event.inputs.version }}-metta-parser
          docker image push trueagi/das:latest-metta-parser

  tag:
    uses: singnet/das/.github/workflows/run-semver.yml@master
    needs:
      - build-image
      - build-binary
    with:
      version: ${{ github.event.inputs.version }}
      version-strategy: bump-version-from-variable-value
      job-image-namespace: trueagi
      job-image-version-semver: semantic-versioning
      main-branch: master
      version-tag-regex-pattern: /^\d+\.\d+\.\d+$/
      version-require-confirmation: "true"
      title: New version of DAS MeTTa Parser
      deliverable: Tagged branch (${{ github.ref_name }}) in the repository
    secrets: inherit
