---
name: DAS Metta Parser Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  tag:
    uses: singnet/das-scripts-pipeline/.github/workflows/action.yml@master
    with:
      version: ${{ github.event.inputs.version }}
      version-strategy: bump-version-from-variable-value
      job-image-namespace: trueagi
      job-image-version-semver: semantic-versioning
      main-branch: master
      version-tag-regex-pattern: /^v\d+\.\d+\.\d+$/
      version-require-confirmation: "true"
    secrets: inherit

  build-binary:
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Dockerfile
        run: ./scripts/docker_image_build.sh

      - name: Build Binary
        run: ./scripts/build.sh

      - name: Upload das-metta-parser artifact
        uses: actions/upload-artifact@v4
        with:
          name: das-metta-parser
          path: bin/das_metta_parser

  build-image:
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Dockerfile
        run: docker build -f ./docker/Dockerfile.toolbox -t trueagi/das:${{ github.event.inputs.version }}-toolbox .

      - name: Push Image to Registry
        run: docker image push trueagi/das:${{ github.event.inputs.version }}-toolbox
